name: Build
on: [push]

jobs:
  build_win:
    runs-on: windows-2019
    steps:
    - name: checkout 
      uses: actions/checkout@v1
    - name: fetch development libraries
      run: | 
        Invoke-WebRequest https://endless-sky.github.io/win64-dev.zip -OutFile win64-dev.zip
        Expand-Archive win64-dev.zip -DestinationPath . -Force
        Remove-Item win64-dev.zip
      shell: powershell
    - name: adjust DIR_ESLIB
      run: (Get-Content .winmake) -replace '^DIR_ESLIB \?=.*$', 'DIR_ESLIB ?= .\dev64' |  Out-File .winmake
      shell: powershell
    - name: fetch mingw-w64
      run: | 
        Invoke-WebRequest https://cfhcable.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z -OutFile mingw.7z
        7z x mingw.7z
        Remove-Item mingw.7z
      shell: powershell
    - name: adjust DIR_MINGW64
      run: (Get-Content .winmake) -replace '^DIR_MINGW64 \?=.*$', 'DIR_MINGW64 ?= .\mingw64\x86_64-w64-mingw32' | Out-File -Encoding UTF8 .winmake
      shell: powershell
    - name: adjust version numbers
      run: |
        (Get-Content source\main.cpp) -replace 'Endless Sky [\d.]+', "Endless Sky Nightly at $env:GITHUB_SHA" | Out-File -Encoding UTF8 source\main.cpp
        (Get-Content credits.txt) -replace 'version [\d.]+', "version nightly-$env:GITHUB_SHA" | Out-File -Encoding UTF8 credits.txt
      shell: powershell
    - name: compile
      run: |
        $ENV:PATH=".\mingw64\bin;$ENV:PATH"
        mingw32-make -f .winmake -j ($(Get-CIMInstance -Class 'CIM_Processor').NumberOfLogicalProcessors) dist
        COPY .\bin\pkgd\EndlessSky.exe EndlessSky.exe
      shell: powershell
    - name: upload .exe
      uses: actions/upload-artifact@master
      with:
        name: EndlessSky-nightly-win64.exe
        path: EndlessSky.exe
    - name: package
      run: |
        COPY .\dev64\bin\* .
        COPY .\mingw64\x86_64-w64-mingw32\lib\libgcc_s_seh-1.dll .
        COPY .\mingw64\x86_64-w64-mingw32\lib\libstdc++-6.dll .
         7z a endless-sky-win64-nightly.zip .\sounds\ .\images\ .\data\ *.dll license.txt keys.txt icon.png EndlessSky.exe credits.txt copyright changelog
      shell: powershell    
    - name: upload full zip
      uses: actions/upload-artifact@master
      with:
        name: endless-sky-win64-nightly.zip
        path: endless-sky-win64-nightly.zip

  build_ubuntu:

    runs-on: ubuntu-18.04
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y g++ scons libsdl2-dev libpng-dev libjpeg-turbo8-dev libgl1-mesa-dev libglew-dev libopenal-dev libmad0-dev
    # TODO: adjust version numbers
    - name: scons build
      run: scons -j $(nproc)
    - name: upload binary
      uses: actions/upload-artifact@master
      with:
        name: endless-sky-nightly-amd64-binary
        path: endless-sky
      
    - name: package
      run: tar -czf endless-sky-amd64-nightly.tar.gz sounds images/ data/ license.txt keys.txt icon.png endless-sky credits.txt copyright changelog
    - name: upload full zip
      uses: actions/upload-artifact@master
      with:
        name: endless-sky-nightly-amd64.tar.gz
        path: endless-sky-nightly-amd64.tar.gz

    - name: scons install
      run: scons -j $(nproc) install DESTDIR=AppDir
    - name: correct absolute paths
      run: sed -i -e 's#/usr#././#g' AppDir/usr/local/games/endless-sky 
    - name: prepare icon
      run: cp icons/icon_512x512.png endless-sky.png
    - name: download linuxdeploy
      run: wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O linuxdeploy && chmod +x linuxdeploy
    - name: create appimage
      run: ./linuxdeploy --appdir AppDir -d endless-sky.desktop -i endless-sky.png -e AppDir/usr/local/games/endless-sky --output appimage
    - name: rename appimage
      run: mv Endless_Sky*.AppImage EndlessSky-nightly-amd64.AppImage
    - name: upload appimage
      uses: actions/upload-artifact@master
      with:
        name: EndlessSky-nightly-amd64.AppImage.zip
        path: EndlessSky-nightly-amd64.AppImage

  build_osx:
    
    runs-on: macOS-10.14
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: install packages
      run: brew install libpng libjpeg-turbo libmad sdl2 7z
    #TODO: adjust version numbers
    - name: build
      run: xcodebuild
    - name: test
      run: |
        brew install tree
        tree build/Release/
    - name: adjust library paths
      run: |
        cd build/Release/Endless\ Sky.app/Contents/MacOS/
        install_name_tool -id "@rpath/libpng16.16.dylib" /usr/local/lib/libpng16.16.dylib
        install_name_tool -id "@rpath/libmad.0.2.1.dylib" /usr/local/lib/libmad.0.2.1.dylib
        install_name_tool -id "@rpath/libturbojpeg.0.dylib" /usr/local/opt/libjpeg-turbo/lib/libturbojpeg.0.dylib
        install_name_tool -id "@rpath/libSDL2-2.0.0.dylib" /usr/local/lib/libSDL2-2.0.0.dylib
    - name: package
      run: 7z a -tzip EndlessSky-nightly-OSX.zip build/Release/Endless\ Sky.app
    - name: upload full zip
      uses: actions/upload-artifact@master
      with:
        name: EndlessSky-nightly-OSX.zip
        path: EndlessSky-nightly-OSX.zip
