name: Build - Windows 2019
on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: fetch development libraries
      run: | 
        Invoke-WebRequest https://endless-sky.github.io/win64-dev.zip -OutFile win64-dev.zip
        Expand-Archive win64-dev.zip -DestinationPath . -Force
        Remove-Item win64-dev.zip
      shell: powershell
    - name: adjust DIR_ESLIB
      run: (Get-Content .winmake) -replace '^DIR_ESLIB \?=.*$', 'DIR_ESLIB ?= .\dev64' |  Out-File .winmake
      shell: powershell
    - name: fetch mingw-w64
      run: | 
        Invoke-WebRequest https://cfhcable.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z -OutFile mingw.7z
        7z x mingw.7z
        Remove-Item mingw.7z
      shell: powershell
    - name: adjust DIR_MINGW64
      run: (Get-Content .winmake) -replace '^DIR_MINGW64 \?=.*$', 'DIR_MINGW64 ?= .\mingw64\x86_64-w64-mingw32' | Out-File -Encoding UTF8 .winmake
      shell: powershell
    - name: adjust version numbers
      run: |
        (Get-Content source\main.cpp) -replace 'Endless Sky [\d.]+', "Endless Sky Nightly at $GITHUB_SHA" | Out-File -Encoding UTF8 source\main.cpp
        (Get-Content credits.txt) -replace 'version [\d.]+', "version nightly-$GITHUB_SHA" | Out-File -Encoding UTF8 credits.txt
      shell: powershell
    - name: compile
      run: |
        $ENV:PATH=".\mingw64\bin;$ENV:PATH"
        mingw32-make -f .winmake -j ($(Get-CIMInstance -Class 'CIM_Processor').NumberOfLogicalProcessors) dist
        COPY .\bin\pkgd\EndlessSky.exe EndlessSky.exe
      shell: powershell
    - uses: actions/upload-artifact@master
      with:
        name: EndlessSky.exe
        path: EndlessSky.exe
    - name: package
      run: |
        COPY .\dev64\bin\* .
        COPY .\mingw64\x86_64-w64-mingw32\lib\libgcc_s_seh-1.dll .
        COPY .\mingw64\x86_64-w64-mingw32\lib\libstdc++-6.dll .
         7z a endless-sky-win64-nightly.zip .\sounds\ .\images\ .\data\ *.dll license.txt keys.txt icon.png EndlessSky.exe credits.txt copyright changelog
      shell: powershell
    - uses: actions/upload-artifact@master
      with:
        name: endless-sky-win64-nightly.zip
        path: endless-sky-win64-nightly.zip
