name: Build - Windows 2019
on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: fetch development libraries
      run: | 
        Invoke-WebRequest https://endless-sky.github.io/win64-dev.zip -OutFile win64-dev.zip
        Expand-Archive win64-dev.zip -DestinationPath . -Force
        Remove-Item win64-dev.zip
      shell: powershell
    - name: adjust DIR_ESLIB
      run: (Get-Content .winmake) -replace '^DIR_ESLIB \?=.*$', 'DIR_ESLIB ?= .\dev64' |  Out-File .winmake
      shell: powershell
    - name: fetch mingw-w64
      run: | 
        Invoke-WebRequest https://cfhcable.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z -OutFile mingw.zip
        Expand-Archive mingw.zip -DestinationPath . -Force
        Remove-Item mingw.zip
      shell: powershell
    - name: adjust DIR_MINGW64
      run: (Get-Content .winmake) -replace '^DIR_MINGW64 \?=.*$', 'DIR_MINGW64 ?= .\mingw64\x86_64-w64-mingw32' | Out-File .winmake
      shell: powershell
